name: careless_whisper
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - annotated-types=0.6.0
  - appdirs=1.4.4
  - asttokens=3.0.0
  - brotlicffi=1.0.9.2
  - ca-certificates=2025.7.14
  - certifi=2025.7.14
  - cffi=1.17.1
  - click=8.1.8
  - comm=0.2.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - docker-pycreds=0.4.0
  - eval_type_backport=0.2.2
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - gitdb=4.0.7
  - gitpython=3.1.43
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libabseil=20250127.0
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libsodium=1.0.20
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.5.1
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - protobuf=5.29.3
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - readline=8.2
  - requests=2.32.4
  - sentry-sdk=2.18.0
  - setproctitle=1.2.2
  - setuptools=78.1.1
  - six=1.17.0
  - smmap=5.0.2
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing=3.10.0.0
  - typing-inspection=0.4.0
  - typing_extensions=4.14.1
  - urllib3=2.5.0
  - wandb=0.21.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - charset-normalizer==3.4.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==4.0.0
      - dill==0.3.8
      - evaluate==0.4.3
      - filelock==3.13.1
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - hf-xet==1.1.5
      - huggingface-hub==0.33.4
      - idna==3.10
      - importlib-resources==6.5.2
      - jinja2==3.1.4
      - jiwer==4.0.0
      - joblib==1.5.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - lightning-utilities==0.14.3
      - llvmlite==0.43.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - multiprocess==0.70.16
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.0
      - openai-whisper==20240930
      - pandas==2.3.1
      - pillow==11.0.0
      - pooch==1.8.2
      - praatio==6.2.0
      - propcache==0.3.2
      - pyarrow==20.0.0
      - pyaudio==0.2.11
      - pycparser==2.22
      - pyparsing==3.2.3
      - pytorch-lightning==2.5.0.post0
      - pytz==2025.2
      - rapidfuzz==3.13.0
      - regex==2024.11.6
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - soundfile==0.12.1
      - soxr==0.5.0.post1
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tiktoken==0.8.0
      - tqdm==4.66.5
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - websockets==15.0.1
      - xxhash==3.5.0
      - yarl==1.20.1
